# Generated by Django 5.2.1 on 2025-06-19 17:50

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogentry',
            old_name='cteated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='categorys',
            old_name='cteated_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
