# Generated by Django 5.2.1 on 2025-08-14 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
