# Generated by Django 5.2.1 on 2025-08-14 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_blogentry_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='blog_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.blogentry'),
        ),
    ]
