# Generated by Django 5.2.1 on 2025-10-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_savedposts_blog_entry_alter_savedposts_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedposts',
            old_name='blog_entry',
            new_name='post',
        ),
    ]
