# Generated by Django 5.2.1 on 2025-10-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_savedposts_post_alter_savedposts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images'),
        ),
    ]
