# Generated by Django 5.2.1 on 2025-10-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_blogentry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog_images'),
        ),
    ]
